### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AkariiinMKII** [brickbots/HandiPi#3]
https://github.com/brickbots/HandiPi/blob/6356b704d89582fd6fa2a959ced833687f7c6ed6/README.md?plain=1#L22

 Here might be `1mm` I guess :P

**Comment by brickbots** [comment]
Haha!  I see the confusion.. it's 1 Newton Meters of force, not nano-meter :-). I just checked and the N should be capitalized, I supposed to avoid this specific issue!
