### ISSUE TITLE
How to build QMK for HandiPi?

### ISSUE THREAD

**Issue by inajob** [brickbots/HandiPi#4]
let me know how to build QMK for this project?

I see https://github.com/manna-harbour/miryoku_qmk/tree/miryoku/users/manna-harbour_miryoku, but I don't know which is best setting for this project.

**Comment by nobodYZH** [comment]
same question.
please help.

**Comment by nobodYZH** [comment]
same problem, can anyone help?

**Comment by brickbots** [comment]
Hi Hi!

Thanks for giving the HandiPi a try!  Sorry for the delayed response, I'm on holiday currently.  I can provide a bit more help when I return, but I have checked in all the QMK files in a branch on my fork:

https://github.com/brickbots/qmk_firmware/tree/handypi/keyboards/handipi

Hopefully this will provide most of what you need.  You can either copy these files into your own fork, or checkout mine and build with the command:

`make clean handipi:manna-harbour_miryoku:flash MIRYOKU_ALPHAS=QWERTY MIRYOKU_NAV=VI`

Replacing which ever Miryoku options you like.  There is also a default keymap to start from if you don't want to use Miryoku.

Hope this helps!  I'll check back in the next day or two to answer any followup questions :-)

**Comment by nobodYZH** [comment]
Thank you for your reply, that helps me a lot!

**Comment by nobodYZH** [comment]
> Hi Hi!
> 
> Thanks for giving the HandiPi a try! Sorry for the delayed response, I'm on holiday currently. I can provide a bit more help when I return, but I have checked in all the QMK files in a branch on my fork:
> 
> https://github.com/brickbots/qmk_firmware/tree/handypi/keyboards/handipi
> 
> Hopefully this will provide most of what you need. You can either copy these files into your own fork, or checkout mine and build with the command:
> 
> `make clean handipi:manna-harbour_miryoku:flash MIRYOKU_ALPHAS=QWERTY MIRYOKU_NAV=VI`
> 
> Replacing which ever Miryoku options you like. There is also a default keymap to start from if you don't want to use Miryoku.
> 
> Hope this helps! I'll check back in the next day or two to answer any followup questions :-)

Thank you for your reply, that helps me a lot!

**Comment by nobodYZH** [comment]
I build qmk and flash the keyboard successfully, and the Miryoku layout works well. But the directional button seems not working.

**Comment by brickbots** [comment]
Hi @nobodYZH !  Thanks for letting me know you got it all up and running.

I didn't include anything for the directional button as it was mapped pretty specifically to my I3WM config and I was not totally sure I implemented it in the 'correct' way to work with Miryoku and

 wanted to review the best practices there.

When I have a bit of time to rework this part of the keymap and make sure it's not going to break other things, I'll push the changes to the same branch.  In the meantime, the directional button is wired up in the matrix as the 5th row and it setup properly in config.h.  Here is how the directions map to the columns:

<img width="161" alt="Screen Shot 2022-11-07 at 9 51 57 AM" src="https://user-images.githubusercontent.com/11450005/200380270-c6af65b1-48bf-4794-b0e1-739b8311fda9.png">

Let me know if you have any other questions I can help with!

**Comment by nobodYZH** [comment]
Hi @brickbots! Everything else runs just perfectly, there are no other questions.
Thank you for your excellent project and I'm looking forward to your future work!

**Comment by inajob** [comment]
Thank you! Mine also worked!
I also had to set fuse bit.

`lfuse 0xEF, hfuse 0xD9, efuse 0xFE`

**Comment by brickbots** [comment]
Hi @inajob !  So glad to hear it worked out for you.  Thanks for letting me know you got it working 👍

**Comment by inajob** [comment]
and I wrote an blog article of making of this keyboard in Japanese.

https://inajob.hatenablog.jp/entry/2023/02/28/HandiPi%E3%81%AE%E6%89%8B%E3%81%AE%E3%81%B2%E3%82%89%E3%82%B5%E3%82%A4%E3%82%BA%E3%81%AE%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89%E3%82%92%E4%BD%9C%E3%81%A3%E3%81%A6%E3%81%BF%E3%81%9F

**Comment by brickbots** [comment]
Hi Hi!

That's a wonderful article!  I had to have it machine translated for me, but it was well ordered and informative.  Thank you for sharing your experience :-D
