### ISSUE TITLE
Issues with V-USB implementation in schematics

### ISSUE THREAD

**Issue by sini6a** [brickbots/HandiPi#5]
Hi brickbots,

You did a fantastic work here and I would really like to try get this thing to work. 

Right now I have some issues with the keyboard. I have flashed usbaspLoader modified to work with Atmega328P used in Plaid keyboard. Everything goes well, I flashed your qmk config on the keyboard but i constantly get some issues with USB resets and HID errors. The strange thing is that this heppens only with the firmware flashed and not while in bootloader.

Other strange thing is that the keyboard works sometimes on my computer while getting HID errors but never on Rasberry Pi 4.

What I tried so far:
1. Changing different fuses on the chip
2. Replacing the chip with new one (tought this could be the issue because I heated the first one badly)
3. Built another new keyboard with 68R instead of 74R
4. Changed USB cable

I am using male USB cable, it is not yet soldered on the Pi, could this maybe related to the errors?

I am stuck and I would be thankful if you have some suggestions for diagnosing this issue.

**Comment by sini6a** [comment]
![image](https://user-images.githubusercontent.com/5903684/201916294-de675144-f5ec-4b17-ad18-2b9c0acc8b89.jpg)

![image](https://user-images.githubusercontent.com/5903684/201916376-d9d2f9b2-935b-4010-828e-7eeb64d8fc6d.jpg)

**Comment by brickbots** [comment]
Hi @sini6a !  Sorry to hear about the bumps you've run into here.  From the photos your build looks very clean and nice and I don't see anything out of place.

As a next step, I would suggest making your USB 'cable' as short as possible.  Normal USB cables are generally well shielded and constructed to prevent interference.  Using bare wires like the HandiPi does, means that the run needs to be as short as possible.  Also try to make the two data lines the same length, within reason.

I had some similar issues with a longer test cable I created and they went away when I made the cable much shorter.  Hopefully this will help you as well!

**Comment by brickbots** [comment]
Just looking a bit closer at your photos... the capacitor in the upper-left (C1) is specified as an electrolytic.  Not sure exactly what the type/value is of the component you've used, but this is part of the power filter/smoothing and it could conceivable lead to some voltage fluctuations if it's not quite right.

I'd definitely suspect the wire/cable length first, but this might be another thing to try if you are still having issues.

**Comment by sini6a** [comment]
Thank you for fast response @brickbots!

The cable length is 15cm. I will try and cut them to half of the current length.

As of the capacitor I think you mean C3 which is located on the upper left corner of the image. It is a 4.7uF radial electrolyte capacitor. I will attach more specification below of the order.

I also noticed that without 1n4148s I got it to work on Raspberry but it was lagging and often stuck on keypress. I think this could be related to USB resets. 

I am trying your suggestions first and I will keep you updated.

Thank you for your time 😊

![7D9EFA1C-EF0E-40D7-B5EB-1322EC6BE223](https://user-images.githubusercontent.com/5903684/202167391-3685bd83-c521-4875-bbad-eb9ce1d4e5d0.png)

![D3CDD0C7-EE8B-4003-8241-2EE0646B5F4F](https://user-images.githubusercontent.com/5903684/202167394-0d30eb98-d08e-49cb-9efb-38208f1072b9.png)

**Comment by brickbots** [comment]
Hi Hi!

Yes, I did mean C3, thank you :-). I've never seen a solid electrolytic before, I'm used to the cylindrical aluminium ones, pretty neat!   That should totally work fine, so hopefully it's just the cable.

It's interesting that it worked without the diodes.... are you referring to D37/D38?  If so, those are not general purpose signal diodes, they are zener diodes to assure that the USB signal lines are 3.6v rather than 5.  My first prototypes without them worked on some devices, but not others, depending on how tolerant the host was of the over-voltage USB data lines.

**Comment by sini6a** [comment]
Hello again 🙂

I was reffering to

**Comment by sini6a** [comment]
Hello again 🙂

Actually I was referring to small signal diodes that should be on the keys. I removed them all and will test without them first. I got them from another supplier and thought that maybe they did some mistake about the model but I will investigate this further when my other order arrives.

Those two diodes sit in place. I will send more specification about them below.

I am still not able to report anything because I was busy these days. Will do it in the weekend latest and report back.

I really appreciate your help and the time spend here trying to resolve the issue. 😊

![4D0ACD49-327F-44A4-8D59-D8A7C58B543E](https://user-images.githubusercontent.com/5903684/202541597-56f1f1f8-9de2-49c2-bb0e-8203b8774a27.png)

**Comment by brickbots** [comment]
Those are definitely the correct Zener diodes!  Good luck with your experiments over the weekend!

**Comment by sini6a** [comment]
Hi again!

No luck so far. I cut the cable half of the length, same problem. 

I tried measuring the voltage on D lines, I am not sure what values should I read but in one of the lines (D+) I get 2.30 idle and 1.20V on key pressed. Other line (D-) has 5.20V idle and 3.20V on key press while measuring with positive side of the usb.

Is it allowed for this line to go over 3.6V?

Sorry if this is irrelevant and my measuring is not correct

Thank you 😊

**Comment by sini6a** [comment]
Okay I have update:

On R2 I installed one more resistor with value of 1.74kOhm and it works like charm. 

I don’t have enough technical knowledge to describe why is it so, maybe someone can explain.

One question that I have right now is does this means that I need to put 3.24kOhm instead of 1.5kOhm?

Thank you so much for your help! 😊

**Comment by sini6a** [comment]
![image](https://user-images.githubusercontent.com/5903684/202812635-755f13fd-390d-477a-a6fc-2ae91704db9a.jpg)

**Comment by brickbots** [comment]
Hi Hi!

So glad it's working, but it's definitely a bit mysterious... R2 pulls the D- line high, indicating that the usb connection is low-speed and 1.5k is the recommended value here.  

Adding resistors in parallel, as the photo indicates, actually produces a lower resistance than either resistor's value.  In this case ~0.8k.... even stranger!   Might be interesting to test the combined resistance without the circuit powered.

As for the D-/D+ voltages, these will be tricky to measure without a good oscilloscope as they will be shifting between low and high states very quickly.  However, it should generally not read above 3.6v.    I'd be curious to know the voltages across the two Zener diodes if you can power the board but leave the signal lines unconnected.

All that aside, if it works, it works!  Glad you worked through the problem and got it sorted :-)

**Comment by sini6a** [comment]
Hi!

Yes, that was the solution in my case, been testing for a whole day and didn’t get a single USB reset. 

Really strange because all schematics on the internet shows 1k5 or 1k7 resistance on the line.

I am traveling this week but I would be happy to do some more tests and report back as soon as I get back. It would be interesting to learn why this board acts like this.

I will close the thread as solved for now. Huge thanks for your help and keep up the good work. This device is brilliant. 😊

**Comment by 199807qwe** [comment]
> Привет, brickbots!
> 
> Вы проделали здесь фантастическую работу, и мне бы очень хотелось попытаться заставить это работать.
> 
> Сейчас у меня проблемы с клавиатурой. Я прошил модифицированный usbaspLoader для работы с Atmega328P, используемым в клавиатуре Plaid. Всё работает хорошо, я прошил вашу конфигурацию QMK на клавиатуру, но постоянно возникают проблемы с перезагрузкой USB и ошибками HID. Странно, что это происходит только после прошивки, а не в режиме загрузчика.
> 
> Ещё одна странность заключается в том, что клавиатура иногда работает на моём компьютере, хотя и выдаёт ошибки HID, но никогда не работает на Raspberry Pi 4.
> 
> Что я уже попробовал:
> 
> 1. Замена различных предохранителей на микросхеме
> 2. Заменил микросхему на новую (подумал, что это может быть причиной проблемы, потому что первую я сильно перегрел).
> 3. Сделал ещё одну новую клавиатуру с 68 символами вместо 74.
> 4. Заменил USB-кабель
> 
> Я использую штекерный USB-кабель, он ещё не припаян к Raspberry Pi. Может ли это быть связано с ошибками?
> 
> Я зашёл в тупик и был бы благодарен за ваши предложения по диагностике этой проблемы.



> Hi brickbots,
> 
> You did a fantastic work here and I would really like to try get this thing to work.
> 
> Right now I have some issues with the keyboard. I have flashed usbaspLoader modified to work with Atmega328P used in Plaid keyboard. Everything goes well, I flashed your qmk config on the keyboard but i constantly get some issues with USB resets and HID errors. The strange thing is that this heppens only with the firmware flashed and not while in bootloader.
> 
> Other strange thing is that the keyboard works sometimes on my computer while getting HID errors but never on Rasberry Pi 4.
> 
> What I tried so far:
> 
> 1. Changing different fuses on the chip
> 2. Replacing the chip with new one (tought this could be the issue because I heated the first one badly)
> 3. Built another new keyboard with 68R instead of 74R
> 4. Changed USB cable
> 
> I am using male USB cable, it is not yet soldered on the Pi, could this maybe related to the errors?
> 
> I am stuck and I would be thankful if you have some suggestions for diagnosing this issue.

Hi friend. Could you please explain step by step how you flashed your keyboard? I'm new to Arduino, so I'd appreciate a step-by-step guide, starting with what I need to buy and how to connect it.
