### ISSUE TITLE
What's the QWERTY keybaord you show in the peripheral  photo?

### ISSUE THREAD

**Issue by CardboardMechanic** [brickbots/HandiPi#6]
I'm curious to know about that small keyboard you show with the computer hooked up to an external display. Do you know the name/model? Was it also a custom keyboard? Thanks!

**Comment by brickbots** [comment]
Hi @TildeWill !  That keyboard is the ChocV a 36key low profile open source keyboard. You can find full plans and such here:
https://github.com/brickbots/chocV

Let me know if you have any questions or want some PCBs, I may still have a set hanging around 👍🏼
